### ISSUE TITLE
Create jar that runs under Windows with Java 11+ installed

### ISSUE THREAD

**Issue by ThomasPause** [IMISE/snik-tag#4]
- [x] is JavaFX deployable?

- [x] if desktop tool, how to build it platform independently

**Comment by ThomasPause** [comment]
- JavaFX is not easily deployable, i think the best way is to convert it to Vaadin Flow , which seems not too hard: https://vaadin.com/docs/v13/flow/introduction/introduction-overview.html
- if desktop tool, there is a javafxpackager inside javafx to do this work, see here: https://jaxenter.de/javafx-tutorial-von-der-klasse-zur-exe-461
- i also found the information that the native java development is delivered automatically with the packed installer, see here: https://www.tecchannel.de/a/mit-javafx-bekommen-java-applikationen-ein-neues-gesicht,2044816 unter dem Punkt: "Installation von Java-Anwendungen wird einfacher"

**Comment by KonradHoeffner** [comment]
I estimate Vaadin conversion to be too time-consuming so I won't do that.
The other posts are from 2014 so there may be better options now.
We now have [jlink](https://docs.oracle.com/en/java/javase/11/tools/jlink.html), which seems to benefit from Java 9 modularization, which we don't have yet.
Even more recently, we got (or will get soon) [jpackage](https://www.baeldung.com/java14-jpackage) with Java 14, which should also be investigated.

**Comment by KonradHoeffner** [comment]
- we need an installer
- one user with Mac, the others use Windows
- bundled with JVM including JavaFX and other libraries
- auto update from Git would be great

**Comment by KonradHoeffner** [comment]
I'm still not sure how to use all of jlink, jpackage and maven together. The plugin <https://github.com/agilhard-oss/jlink-jpackager-maven-plugin> seems promising but needs to be manually installed and cannot be found yet even after a successful local install via download and `mvn install`.

**Comment by KonradHoeffner** [comment]
After much investigation and trial and error with the maven dependency and .jar plugins, I was finally able to create a runnable .jar file using the maven assembly plugin and some fixes. Filesize is 64 Mib. For a short guide on how to use those plugins, see <https://www.baeldung.com/executable-jar-with-maven>.

Next steps:
- [ ] create windows-jars as well (JavaFX binaries are platform-specific)
- [ ] either tell the users to install Java 14 (downgrade to 11?) and give them the jar or continue with jlink, jpackage and so on

**Comment by KonradHoeffner** [comment]
Note: jpackage replaces jpackager. Don't confuse the two, use jpackage.

**Comment by KonradHoeffner** [comment]
[This post](https://stackoverflow.com/questions/52653836/maven-shade-javafx-runtime-components-are-missing) explains how to set the operating systems of the produced jar. However it seems to be written for an older version.

**Comment by KonradHoeffner** [comment]
I checked the Windows PC baramundi Kiosk but Java is only available at version 8 and the code needs at least Java 11. This means we cannot just create the jar, we either need to bundle a portal JRE with it or use jpackage.

**Comment by KonradHoeffner** [comment]
I tried it on the Windows computer using a portable Java 14 from https://portableapps.com/apps/utilities/OpenJDK64 but even with the "win" classifier on all JavaFX Maven dependencies there is an error:

`java -jar sniktag.jar                                                                   Graphics Device initialization failed for :  d3d, sw                                                                 Error initializing QuantumRenderer: no suitable pipeline found                                                       java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found                                                                                                                            at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)                                   at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)                                            at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)                                                            at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)                                            at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)                                            at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)                                       at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)                                 at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)                         at java.base/java.lang.Thread.run(Thread.java:832)                                                           Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found                        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)                          at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)                          ... 1 more                                                                                                   Exception in thread "main" java.lang.RuntimeException: No toolkit found                                                      at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)                                                            at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)                                            at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)                                            at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)                                       at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)                                 at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)                         at java.base/java.lang.Thread.run(Thread.java:832)                                                                                                                                 
`

**Comment by KonradHoeffner** [comment]
Trying out [jpackage](https://docs.oracle.com/en/java/javase/14/docs/specs/man/jpackage.html) right now, unfortunately "app-image" seems to be the only supported option on Arch Linux.

**Comment by KonradHoeffner** [comment]
Going down the rabbit hole of jpackage, jpackager, javapackage, jlink, JavaFX, JMODs and JARs is quote confusing, investigating more...

**Comment by KonradHoeffner** [comment]
There seems to be no current way crosscompile from Linux to Windows, see https://stackoverflow.com/questions/58675893/is-there-a-way-to-build-installers-for-a-java-application-for-multiple-targets-o. Docker might be needed.

**Comment by KonradHoeffner** [comment]
I finally got it to work by including the "javafx-graphics" dependency and adding the "win" classifier to all JavaFX dependencies. Then execute the portable 64 bit installer https://portableapps.com/apps/utilities/OpenJDK64, extract into "OpenJDK64" and call OpenJDK64\bin\java -jar sniktag.jar.

This still involves some manual work but at least it works at all on a no-admin-rights Windows machine with only Java 8 available.

**Comment by KonradHoeffner** [comment]
Portable windows application of a master branch snapshot available at https://github.com/IMISE/snik-tag/releases/download/0.2.1/sniktag.zip.
