### ISSUE TITLE
Dealing with synonyms in the text

### ISSUE THREAD

**Issue by FranziskaJahn** [IMISE/snik-tag#8]
Sometimes, the authors introduce a term for concept together with synonyms. There needs to be a possibility to capture these synonyms in SNIK-Tag.

**Comment by KonradHoeffner** [comment]
We typically use a set of alternative labels for that purpose in SNIK. For ease of use, we could also just use a single list for the labels and the first one becomes the label at the end.
Showing a multiple values in the class table is no problem as we already do that for the relation. The problem is how to edit that.

**Comment by KonradHoeffner** [comment]
Decision meeting 2019-07-19: use multiple labels.

**Comment by KonradHoeffner** [comment]
- [x] classes have a set of labels
- [x] the set of labels is shown appropriately in the class table
- [x] the set of labels can be edited in the class table
- [x] the labels are properly converted to RDF
- [x] the labels are properly handled in the class text area
- [x] the labels are properly shown in the relation pane (adapt Clazz::toString())
- [x] add class merge option to table

Note: Multiple labels is not the usual SNIK style. Until now, we had at least one label, one at most per language, and the rest is modelled as skos:altLabel. We could still convert it differently at the end but then we have to identify the label against the altLabel. Probably the first one is the label. However if we have a set we don't preserve order in Java.
